server:
    port: 8089
    servlet:
        context-path: /ad


#mysql数据库连接
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/adexamine?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource

    mvc:
        view:
            prefix: /
            suffix: .html
        static-path-pattern: /static/**
        favicon:
            enabled: true

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        cache: false


mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
    mapper-locations: classpath:/mapper/*Mapper.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.ahu.ad.exam.entity,com.ahu.ad.exam.vo
    # 显示SQL
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl